CREATE TABLE foods
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255),
    image VARCHAR(255),
    price DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_foods PRIMARY KEY (id)
);